### ISSUE TITLE
Add Copyright and license section to bottom of README

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iab-spiders-and-robots-java-client#3]
See e.g. https://github.com/snowplow/schema-guru#copyright-and-license

**Comment by vt-kechko-hfs** [comment]
Added Copyright and license section to README

**Comment by alexanderdean** [comment]
License link is broken due to GH's recent switch to CommonMark

**Comment by v-ladynev-hfs** [comment]
@alexanderdean fixed, sorry for that
