### ISSUE TITLE
Set up CI/CD for repo

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iab-spiders-and-robots-java-client#4]

**Comment by ninjabear** [comment]
The first step is a `.travis.yml` with the following in:

```{yaml}
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
```

This should cover the CI part by running `gradle check` each time the repo is pushed to, and for PRs.

**Comment by ninjabear** [comment]
The easiest way to get things shipped with gradle is the [gradle bintray plugin](https://github.com/bintray/bintray-examples/tree/master/gradle-example). This is the next step after the creds are covered

**Comment by v-ladynev-hfs** [comment]
@ninjabear I have added Travis support. But we have a build error `/home/travis/build.sh: line 229: ./gradlew: Permission denied`. Also, do we need this: ` - openjdk7`?

**Comment by alexanderdean** [comment]
Is there a missing chmod +x on ./gradlew?

**Comment by v-ladynev-hfs** [comment]
@alexanderdean Yes. You are right. It works now. Thank you for help.

**Comment by alexanderdean** [comment]
np!

**Comment by v-ladynev-hfs** [comment]
Looks like, bintray upload task is done. I have checked it using my test bintray account and Travis deploy task, triggered on pushing a repo tag. 

We have two Travis  builds for JDK 7 and JDK 8. JDK 7 deploy was successful and JDK 8 deploy was failed.

**Comment by alexanderdean** [comment]
Are you asking for help on the failed build?

**Comment by v-ladynev-hfs** [comment]
@alexanderdean This is just for your information. Probably, it is impossible to have two concurrent deploying processes. I just don't know. Does it suitable?

**Comment by alexanderdean** [comment]
@ninjabear can advise! Also @ninjabear - can you make sure this artifact is making it through to Maven Central?

**Comment by v-ladynev-hfs** [comment]
@ninjabear Just for your information. We have 0.1.0 version in the `gradle.build` now.

**Comment by ninjabear** [comment]
Ah, yes sorry we only want to run the deployment from the jdk7 build. There's an environment variable set in the build for this:

`TRAVIS_JDK_VERSION` must be equal to `oraclejdk7`

This can be an "on" condition in `.travis.yml` like this:

```
deploy:
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy.sh $TRAVIS_TAG
    on:
      tags: true
      condition: "$TRAVIS_JDK_VERSION = oraclejdk7"
```

**Comment by alexanderdean** [comment]
Thanks @ninjabear - also please note @v-ladynev-hfs - generally we only push the 0.1.0 at the very very last minute, when all QA is done and we have validated that things are working correctly. You're now in the situation where you are going to have to force push and overwrite the definition of 0.1.0, which is ugly.

**Comment by v-ladynev-hfs** [comment]
Everything is working now

JDK7 https://travis-ci.org/snowplow/iab-spiders-and-robots-java-client/jobs/216695219

JDK8 https://travis-ci.org/snowplow/iab-spiders-and-robots-java-client/jobs/216695220

@alexanderdean I set `0.1.0-rc1` version

**Comment by alexanderdean** [comment]
Thanks @v-ladynev-hfs! @ninjabear please update this ticket once we have the rc1 in Maven Central!

**Comment by ninjabear** [comment]
@alexanderdean 0.1.0-rc1 is now in JCenter - it should appear on [Maven Central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.snowplowanalytics%22) in a few hours (maybe sooner)

**Comment by alexanderdean** [comment]
Legend, thanks @ninjabear

**Comment by alexanderdean** [comment]
It's in! Thanks all, closing this ticket

http://search.maven.org/#artifactdetails%7Ccom.snowplowanalytics%7Ciab-spiders-and-robots-client%7C0.1.0-rc1%7Cjar
