### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iab-spiders-and-robots-java-client#7]
* [x] Finalize release date in CHANGELOG - **today, 3 April**
* [x] Finalize version to 0.1.0
* [x] Squash git history back to "Initial commit"

**Comment by v-ladynev-hfs** [comment]
Uploaded only to bintray https://bintray.com/snowplow/snowplow-maven/iab-spiders-and-robots-client/0.1.0

For Maven we have a Travis error:

What went wrong:
Execution failed for task ':bintrayUpload'.
Could not sync 'snowplow/snowplow-maven/iab-spiders-and-robots-client/0.1.0' to Maven Central: HTTP/1.1 400 Bad Request [messages:[Problem extracting files to sync. Please try again in a bit.], status:Sync Failed]

**Comment by alexanderdean** [comment]
One for @ninjabear

**Comment by alexanderdean** [comment]
@ninjabear what happened here? Can we try and get this released to Maven Central?

**Comment by ninjabear** [comment]
Looks like mavencentral had a hiccup! I have ran the sync manually

**Comment by alexanderdean** [comment]
Thanks @ninjabear ! Closing this issue then...
